name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: 'Install Node'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - name: 'Install Deps'
      run: yarn install --immutable
    - name: 'Build'
      run: yarn build
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: 'Install Node'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
    - name: 'Install Deps'
      run: yarn install --immutable
    - name: 'Lint'
      run: npm run lint
    - name: 'Typecheck'
      run: npm run typecheck
    - name: 'Test'
      run: npm run test